[tools]
"go:github.com/standardbeagle/mcp-clip" = "latest"
"go:github.com/karol-broda/snitch" = "latest"
cargo-binstall = "latest"
"cargo:usage-cli" = "2.12.0"
"cargo:markdown-extract-cli" = "latest"
"github:railwayapp/railpack" = "latest"
"github:railwayapp/cli" = "latest"
"dive" = "latest"

[settings]
experimental = true

[settings.cargo]
binstall = true

[settings.pipx]
uvx = true
