[tools]
"go:github.com/standardbeagle/mcp-clip" = "latest"
"go:github.com/karol-broda/snitch" = "latest"
cargo-binstall = "latest"
"cargo:usage-cli" = "2.12.0"
"cargo:ast-grep" = "latest"
"cargo:fastmod" = "latest"
"cargo:markdown-extract-cli" = "latest"
"github:railwayapp/railpack" = "latest"
"github:railwayapp/cli" = "latest"
"dive" = "latest"
# micro is rarely updated on github, so we use the nightly build
"github:zyedidia/micro" = "nightly"

[settings]
experimental = true

[settings.cargo]
binstall = true

[settings.pipx]
uvx = true
